---
- name: Update all packages
  yum:
    name: '*'
    state: latest
  become: yes


- name: Install Go
  unarchive:
    src: https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz
    remote_src: yes
    dest: /usr/local/
  become: yes

- name: Add Go to path
  lineinfile:
    path: ~/.bash_profile
    line: 'export PATH=$PATH:/usr/local/go/bin'

- name: Symlink Go to /usr/bin for SSH shells
  file:
    src: /usr/local/go/bin/go
    dest: /usr/bin/go
    state: link
  become: yes

- name: Install Packages
  yum:
    name: [git, vim, tree, tmux]
  become: yes

- name: Install github hub tool
  shell: |
     cd /tmp
     curl -L https://github.com/github/hub/releases/download/v2.12.0/hub-linux-amd64-2.12.0.tgz | tar xfz -
     cd hub-linux-amd64-2.12.0
     ./install
  become: yes
