---
helm_version: v2.14.1
helm_url: https://storage.googleapis.com/kubernetes-helm/helm-{{ helm_version }}-linux-amd64.tar.gz
submariner_broker_ns: submariner-k8s-broker
submariner_psk: Shovmi3sLfeL926zS5PicfCPZ22UPoFsWUkRHBRGpRHDWstwEmKPXaS5sVeBtgaj