---
- name: Update all packages
  yum:
    name: '*'
    state: latest
  become: yes

- name: Install Packages
  yum:
    name: [docker, pyOpenSSL]
    state: present
  become: yes

- name: Enable docker service
  service: name=docker state=started enabled=yes
  become: yes

