{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "submariner.fullname" . }}:engine
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "submariner.chart" . }}
    app: {{ template "submariner.name" . }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "get", "list", "watch", "patch", "update"]
- apiGroups: ["submariner.io"]
  resources: ["clusters", "endpoints"]
  verbs: ["create", "get", "list", "watch", "patch", "update", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "submariner.fullname" . }}:routeagent
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "submariner.chart" . }}
    app: {{ template "submariner.name" . }}
rules:
- apiGroups: ["submariner.io"]
  resources: ["clusters", "endpoints"]
  verbs: ["create", "get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "submariner.fullname" . }}:engine
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "submariner.fullname" . }}:engine
subjects:
- kind: ServiceAccount
  name: {{ template "submariner.engineServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "submariner.fullname" . }}:routeagent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "submariner.fullname" . }}:routeagent
subjects:
- kind: ServiceAccount
  name: {{ template "submariner.routeAgentServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
