apiVersion: charts.helm.k8s.io/v1alpha1
kind: Submariner
metadata:
  name: example-submariner
spec:
  # Default values copied from <project_dir>/helm-charts/submariner/values.yaml
  
  submariner:
    clusterId: ""
    token: ""
    clusterCidr: "10.42.0.0/16"
    serviceCidr: "10.43.0.0/16"
    natEnabled: false
    colorCodes: blue
    debug: false
  crd:
    create: true
  broker:
    type: k8s
    server: example.k8s.apiserver
    token: test
    namespace: submariner-k8s-broker
    insecure: false
    ca: ""
  rbac:
    create: true
  ipsec:
    psk: ""
    debug: false
  engine:
    image:
      repository: rancher/submariner
      tag: v0.0.1
      pullPolicy: Always
    resources: {}
      # limits:
      # cpu: 100m
    # memory: 100Mi
    nodeSelectorEnabled: true
    nodeSelector: {}
    tolerations: []
    affinity: {}
  routeAgent:
    image:
      repository: rancher/submariner-route-agent
      tag: v0.0.1
      pullPolicy: Always
    resources: {}
      # limits:
    # cpu: 100m
    # memory: 100Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}
  serviceAccounts:
    engine:
      create: true
      name: ""
    routeAgent:
      create: true
      name: ""
