---
- name: Wait for ssh connection
  wait_for_connection:
    timeout: 300

- name: Wait for tiller to become created
  become: false
  shell: "kubectl get pods -n kube-system -l app=helm --output=jsonpath='{.items[*].metadata.name}'"
  register: helm_pods_created
  until: helm_pods_created.stdout
  retries: 30
  delay: 30

- name: Wait for tiller to become ready
  become: false
  shell: "kubectl wait -n kube-system --for=condition=Ready pods -l app=helm --timeout=600s"
  register: helm_pods_ready

- debug: var=helm_pods_ready.stdout_lines

- name: Tag gateway node
  become: false
  shell: kubectl label node {{ gateway_node }} "submariner.io/gateway=true"
  register: result
  changed_when: "'labeled' in result.stdout"
  failed_when: "result.rc != 0 and 'already has a value' not in result.stderr"

- name: Update helm repos
  become: false
  command: helm repo update
  register: result
  changed_when: "'\"submariner-latest\"' in result.stdout"
  failed_when: "result.rc != 0 or '\"submariner-latest\"' not in result.stdout"

- name: Install submariner gateway node
  become: false
  command: |
    helm install submariner-latest/submariner \
    --name submariner \
    --namespace submariner \
    --set ipsec.psk="{{ submariner_psk }}" \
    --set broker.server="{{ submariner_broker_url }}" \
    --set broker.token="{{ submariner_broker_token }}" \
    --set broker.namespace="{{ submariner_broker_ns }}" \
    --set broker.ca="{{ submariner_broker_ca }}" \
    --set submariner.clusterId="{{ cluster_name }}" \
    --set submariner.clusterCidr="{{ pod_cidr }}" \
    --set submariner.serviceCidr="{{ service_cidr }}" \
    --set submariner.natEnabled="true"
  register: gateway_result
  changed_when: "'created' in result.stdout"
  failed_when: "result.rc != 0 and 'submariner already exists' not in result.stderr"

- name: Wait for submariner-engine to become created
  become: false
  shell: "kubectl get pods -n submariner -l app=submariner-engine --output=jsonpath='{.items[*].metadata.name}'"
  register: engine_pods_created
  until: engine_pods_created.stdout
  retries: 30
  delay: 30

- name: Wait for submariner-engine to become ready
  become: false
  shell: "kubectl wait -n submariner --for=condition=Ready pods -l app=submariner-engine --timeout=600s"
  register: engine_pods_ready

- debug: var=engine_pods_ready.stdout_lines

- name: Wait for submariner-routeagent to become created
  become: false
  shell: "kubectl get pods -n submariner -l app=submariner-routeagent --output=jsonpath='{.items[*].metadata.name}'"
  register: routeagent_pods_created
  until: routeagent_pods_created.stdout
  retries: 30
  delay: 30

- name: Wait for submariner-routeagent to become ready
  become: false
  shell: "kubectl wait -n submariner --for=condition=Ready pods -l app=submariner-routeagent --timeout=600s"
  register: routeagent_pods_ready

- debug: var=routeagent_pods_ready.stdout_lines

